version: '3'
services:
  server: 
    image: multiwordle-server 
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "2568:2568"


  app:
    image: multiwordle-app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - "8091:80"

  redis:
    image: redis
    restart: unless-stopped