# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0

jobs:
  build-images:
    #working_directory: ~/project/app
    docker:
      - image: docker:19.03-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.14
      - run:
          name: Build application Docker image
          command: |
            docker build -t app ./app
      - run:
          name: Build server Docker image
          command: |
            docker build -t server ./server
      - run:
          name: Upload to docker registry
          command: |
            echo "$DOCKER_REGISTRY_PASS" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin "$DOCKER_REGISTRY"
            docker tag server $DOCKER_REGISTRY/multiwordle-server
            docker tag app $DOCKER_REGISTRY/multiwordle-app
            docker push $DOCKER_REGISTRY/multiwordle-server
            docker push $DOCKER_REGISTRY/multiwordle-app
  test:
    docker:
      - image: cimg/node:17.4
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/app
          pkg-manager: npm
      - run:
          name: Run tests
          command: cd ~/project/app && npm test

workflows:
  build:
    jobs:
      - test
      - build-images:
          requires:
            - test
          filters:
            branches:
              only:
                - master